name: Deploy Portfoloi Container to MicroK8s

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Portfolio Container Image
        run: |
          docker build -t elmi08/portfolio:latest .

      - name: Login to Docker Hub 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Portfolio Container to Docker Hub
        run: |
          docker push elmi08/portfolio:latest

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
      
      - name: Deploy Frontend to MicroK8s
        run: |
          kubectl apply -f deployment-service.yaml